# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopopyProfiler
                                 A QGIS plugin
 This plugin shows the geomorphic index profile
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-31
        copyright            : (C) 2021 by David
        email                : davidglezojgo@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TopopyProfiler class from file TopopyProfiler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .topopy_profiler import TopopyProfiler
    return TopopyProfiler(iface)
